export const allowedTools = [
  "create_project",
  "import_assets",
  "inspect_asset",
  "get_timeline",
  "patch_timeline",
  "validate_timeline",
  "preview_range",
  "render_export",
  "open_preview",
  "update_project_intent",
  "get_project_review",
  "list_versions",
  "compare_versions",
  "provider_readiness_reminder",
  "get_creative_preferences",
  "update_creative_preferences",
  "prepare_reference_asset",
  "enhance_asset_prompt",
  "submit_creative_asset_job",
  "get_creative_asset_job",
  "import_creative_asset_job",
  "import_comfyui_workflow",
  "list_comfyui_workflows",
  "get_comfyui_workflow"
] as const;
